### ISSUE TITLE
Consumer thinks there is data available after connection breaks

### ISSUE THREAD

**Issue by Shaa1** [stomp-php/stomp-php#104]
I have a consumer waiting for messages and when the sender is shutdown (in my case ActiveMQ), the StatefulStomp::read() method starts to always return false without waiting and without throwing exception.
Since I call read() in a loop, it starts looping really fast.

I think the problem is that the method Connection::hasDataToRead() return true because the socket can be read, but there is actually no data, just an empty string, meaning that the connection broke.
Maybe a ConnectionException should be thrown?

**Comment by jmglsn** [comment]
Have you tried to use Heartbeats?
I'll create a test case for this tomorrow.

**Comment by Shaa1** [comment]
Yes but it doesn't change anything.

**Comment by jmglsn** [comment]
Yes, the client based check is not available yet and I also managed to see the state that you described. Didn't find the time to fix it today, hope I can manage this at Monday.

**Comment by jmglsn** [comment]
Started to work on this, I'll need to update the test case.
Just throwing an exception when we don't receive data there will break some of them.

**Comment by jmglsn** [comment]
Ok, I'll need to rewrite the connection to use plain socket functions, on stream level it's almost impossible to solve this, as some very basic functionality is not working. see https://bugs.php.net/bug.php?id=52811

**Comment by jmglsn** [comment]
This is fixed in version `4.4.0` see https://github.com/stomp-php/stomp-php/releases/tag/4.4.0
