### ISSUE TITLE
[HELP] I get always  Error "Bad CONNECT" 

### ISSUE THREAD

**Issue by xgc1986** [stomp-php/stomp-php#105]
That is my code, I tried different tutorials, but I always receive the same error when I call send method

        $stomp = new SimpleStomp(new Client('tcp://localhost:61613'));

        $stomp->send(
            '/topic/test',
            new Bytes($input->getArgument('message'))
        );

![screenshot from 2018-02-13 00-41-06](https://user-images.githubusercontent.com/1313235/36125962-a290a73e-1056-11e8-8da6-ba81d37cab7d.png)

and my rabbit.config file is
```
[{rabbit, [
            {auth_backends, [rabbit_auth_backend_internal]}
          ]
},
  {rabbitmq_stomp, [{tcp_listeners, [{"0.0.0.0", 61613},
                                     {"::1",       61613}]},
                                     {default_vhost, <<"/">>},
                                     {default_user, [{login, "guest"},{passcode, "guest"}]},
                                     {implicit_connect, true}
   ]}
].
```
the log message is

```
=INFO REPORT==== 13-Feb-2018::00:42:53 ===
accepting AMQP connection <0.1084.0> (127.0.0.1:43130 -> 127.0.0.1:5672)

=INFO REPORT==== 13-Feb-2018::00:42:53 ===
connection <0.1084.0> (127.0.0.1:43130 -> 127.0.0.1:5672): user 'root' authenticated and granted access to vhost '/'

=INFO REPORT==== 13-Feb-2018::00:42:53 ===
accepting STOMP connection <0.1094.0> (127.0.0.1:44070 -> 127.0.0.1:61613)

=WARNING REPORT==== 13-Feb-2018::00:42:53 ===
STOMP login failed - not_allowed (vhost access not allowed)

=ERROR REPORT==== 13-Feb-2018::00:42:53 ===
STOMP error frame sent:
Message: "Bad CONNECT"
Detail: "Virtual host 'localhost' access denied"
Server private detail: none

=INFO REPORT==== 13-Feb-2018::00:42:53 ===
closing STOMP connection <0.1094.0> (127.0.0.1:44070 -> 127.0.0.1:61613)

=INFO REPORT==== 13-Feb-2018::00:42:53 ===
closing AMQP connection <0.1084.0> (127.0.0.1:43130 -> 127.0.0.1:5672, vhost: '/', user: 'root')

```

**Comment by staabm** [comment]
maybe your queue does make a difference between `::1` and `localhost`. did you try to connect to `::1` ?

**Comment by jmglsn** [comment]
Looks like your queue is protected by username and password, so you need to login before you can start using it.

You find an example for rabbit with vhost at https://github.com/stomp-php/stomp-php/blob/master/tests/Functional/RabbitMq/ClientProvider.php#L31

As more generic example can be found here:
See examples https://github.com/stomp-php/stomp-php-examples/blob/support/version-4/src/security.php#L34


```php
        $client = new Client(new Connection('tcp://127.0.0.1:61030'));
        $client->setLogin('guest', 'guest');
        $client->setVhostname('/');
```

**Comment by xgc1986** [comment]
I tried that but I had the same error

**Comment by jmglsn** [comment]
It seems that the configuration for `loopback_users` is not ok.
By default and for security reasons the default configuration don't allow user guest to connect from anywhere else than from the direct host loopback.
You can try to change the config to something like `{loopback_users, []}` but please only use this for local tests. In production you need another user.

**Comment by jmglsn** [comment]
@xgc1986 did this work for you?
