### ISSUE TITLE
Broken link in wiki

### ISSUE THREAD

**Issue by dpashin** [stomp-php/stomp-php#108]
There is a link at the end of https://github.com/stomp-php/stomp-php/wiki/Transactions : 

> The full example of the transaction usage with PHP Stomp client can be found in examples/transactions.php.

a link to https://github.com/stomp-php/stomp-php/blob/master/examples/transactions.php is broken (404)

**Comment by jmglsn** [comment]
Thanks for reporting, we need to renew the wiki. 
We moved the examples to a own repository. 
You find the linked example at https://github.com/stomp-php/stomp-php-examples/blob/support/version-4/src/transactions.php
