### ISSUE TITLE
Set username and password

### ISSUE THREAD

**Issue by darkmatus** [stomp-php/stomp-php#109]
Actually it is not possible to set a username and a password for connections. This should be possible because some systems a connected to the whole internet and no one will have an open queue system where everone can send messages to.

Is it possible to implement this or are there already options to set it (have not found anything)?

**Comment by jmglsn** [comment]
Hi @darkmatus,
we support setting credentials, you can find an entry here in our examples.
https://github.com/stomp-php/stomp-php-examples/blob/support/version-4/src/security.php#L34

Let us know if this helps you.

BR
Jens

**Comment by darkmatus** [comment]
Okay, havn't seen it as i viewed the examples. ._. Thanks

**Comment by jmglsn** [comment]
You're welcome :)
