### ISSUE TITLE
Scan code with PHPMD

### ISSUE THREAD

**Issue by chuhlomin** [stomp-php/stomp-php#11]
... and fix what possible without huge refactoring.

**Comment by jmglsn** [comment]
All those typos, my favorite is `diconnect`  :+1:  
Just fixed two tests in 6ce55399165dd98a276b9e71aea0847bd808f1d8.
I'm still busy working on the roof for a friend, hope I'll finish that next week..

**Comment by jmglsn** [comment]
Thank you!
