### ISSUE TITLE
Connecting to Stomp on AmazonMq Using stomp-php

### ISSUE THREAD

**Issue by deltastateonline** [stomp-php/stomp-php#114]
We had a lot of problems connecting to stomp on amazonMq, Amazonmq requires you use "stomp-ssl" which doesn't seem to be valid scheme.

We were able to overcome this by using tls protocol and disabling verify_peer.
here is a code snippet which we used
[https://gist.github.com/deltastateonline/efc9ddfb811cba3f11614e149c90b5e9](Gist Snippet)

**Comment by jmglsn** [comment]
I can't recommend doing so. In my tests with AWS I was able to use full featured ssl connections, please check if https://github.com/stomp-php/stomp-php/pull/118 helps you to revert setting verify_peer to false.

**Comment by jmglsn** [comment]
With 4.5.0 we don#t see any problems with AWS MQ / SSL enabled. Please don't disable ssl security features, the client will and must work with enabled security restrictions.
