### ISSUE TITLE
Unexpected response received. Expected receipt id xxx - AmazonMQ

### ISSUE THREAD

**Issue by mlamm** [stomp-php/stomp-php#115]
I am using this library (version: 4.4.1) to connect to a Amazon-MQ Backend.
In general this just works fine, however, from time to time I get random errors in the form of:

```
Stomp\Exception\UnexpectedResponseException: Unexpected response received. Expected receipt id 45lkj234l5jk23l5 (uncaught exception) at /var/www/vendor/stomp-php/stomp-php/src/Client.php line 320
```

I am left quite clueless, any advice here?

**Comment by mlamm** [comment]
The error seems to be prepended by:
```Stomp\Exception\ConnectionException: Was not possible to read data from stream. (Host: blehfdafljljk2l3j234.mq.eu-central-1.amazonaws.com) in /var/www/vendor/stomp-php/stomp-php/src/Network/Connection.php:473
Stack trace:
#0 /var/www/vendor/stomp-php/stomp-php/src/Client.php(315): Stomp\Network\Connection->readFrame()
#1 /var/www/vendor/stomp-php/stomp-php/src/Client.php(299): Stomp\Client->waitForReceipt('gggg34g3g4g34g4g...')
#2 /var/www/vendor/stomp-php/stomp-php/src/Client.php(281): Stomp\Client->sendFrameExpectingReceipt(Object(Stomp\Transport\Frame))```

**Comment by jmglsn** [comment]
@mlamm Did you try to update to 4.4.3? If I'm not wrong #111 and #114 are also AWS related.

**Comment by jmglsn** [comment]
@mlamm did the update help you?
If not could you give me some details about how the queue itself is configured and from where you connect? I would like to start some tests, as the last reported errors are all related to AWS.

**Comment by mlamm** [comment]
I updated to 4.4.3, no longer entirely sure if 4.4.1 was even running, however, I notice an increased error rate now.

There's a Active/Standy Broker in place (https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/active-standby-broker-deployment.html). We also used to have issues here when the active broker switched, that's a different issue and probably not related.

The configuration is pretty much out of the box (from what AWS gives you).

I tried this (https://github.com/stomp-php/stomp-php/pull/111#issuecomment-456415791) for further debugging, but can't find any openssl-related errors now.

A quick test shows that "fat" messages, in my example ~250kB cause this issue.

**Comment by mlamm** [comment]
I reverted to *4.3.1*, then it works just fine (at least for now).

**Comment by jmglsn** [comment]
@mlamm I also tested with a 3 node setup yesterday on AWS faced no SSL errors but many read errors - that I was able to fix on a local development branch, hope that I find some time this evening to provide a preview for 4.5 that will fix some issues regarding false read errors...
You're only affected by unexpected receipt errors or?

**Comment by mlamm** [comment]
I think the main-issue here is:

```
Stomp\Exception\ConnectionException: Was not possible to read data from stream. (Host: b-x-x-x-x-x-2.mq.eu-central-1.amazonaws.com) (uncaught exception) at /var/www/vendor/stomp-php/stomp-php/src/Network/Connection.php line 473
```

I could reliable destroy the queue-processing (stomp-php + some php-code, processing items from the queue) by throwing a 250 kByte message on the queue.

I guess the receipt error is a follow-up error to the "can't read from queue"-error.

**Comment by jmglsn** [comment]
Ok, than the fix should address this, I'll add some additional tests as it could bring back the problem with undetected dead servers - so I had to add better support for heartbeats. 
But I need to add more test cases, you'll find a release candidate tomorrow here. 
Thanks for the details

**Comment by jmglsn** [comment]
You can try `dev-bugfix/connection-read-errors` as composer dependency, I'll release this as `4.5.0` after I added support for checking for server based heartbeats (and delay).

Right now this will not longer fail with false broken connection detection, but it will also not detect a broken server in case. That's the reason why it makes sense to use client based heartbeats to check the connection. (until the moment the server heartbeat feature is implemented)
```php
$connection = new \Stomp\Network\Connection(....);
$client = new Client($connection);
// we will send heartbeats or frames every 2 s
$client->setHeartbeat(2000, 0);
$emitter = new \Stomp\Network\Observer\HeartbeatEmitter($connection);
// now the client will detect a dead server when it fails sending heartbeats
```

**Comment by jmglsn** [comment]
I created https://github.com/stomp-php/stomp-php/pull/118 for this. I would suggest to use the `ServerAliveObserver` to detect a dead server now.

**Comment by mlamm** [comment]
I tested this today, **4.5.0-RC1** fixes the issue I had, thanks for all the support, much appreciated.

Will look into Heartbeat/ServerAliveObserver to detect (silent) AmazonMQ Master/Slave-Switches, which they do from time to time.
