### ISSUE TITLE
Bug: Waiting for socket after receiving OS signals

### ISSUE THREAD

**Issue by edefimov** [stomp-php/stomp-php#117]
Situation: the `Stomp\Client` is working inside the daemon, and the daemon receives _TERM_ signal. PHP async signals option is turned on. 
Right after signal the `stream_select` call at [Connection.php:556](https://github.com/stomp-php/stomp-php/blob/4.4.3/src/Network/Connection.php#L556) is returned with `false` result. After return from `isDataOnStream` the method [connectionHasDataToRead](https://github.com/stomp-php/stomp-php/blob/4.4.3/src/Network/Connection.php#L540) will continue to wait until it reaches read timeout. 
In such a case `connectionHasDataToRead` should immediately return false for proper application terminating.

**Comment by jmglsn** [comment]
That's a good point. I'll check if I can add it to the PR for 4.5.0.

**Comment by jmglsn** [comment]
Added this: https://github.com/stomp-php/stomp-php/pull/118/commits/61f8cd1d6d734a15154494129a45277f45c18b7e

**Comment by jmglsn** [comment]
Solved with version 4.5.0 see also https://github.com/stomp-php/stomp-php-examples#signal-processing-pcntl
Thanks for reporting :+1:
