### ISSUE TITLE
setup prettyci and remove squizlabs/php_codesniffer dependency

### ISSUE THREAD

**Issue by staabm** [stomp-php/stomp-php#123]
hopefully we get a faster CI build with less wasted time while installing dependencies.

we should use https://prettyci.com/ instead which is free for open source projects and a lot faster then a travis based CS build

**Comment by jmglsn** [comment]
Didn't know about prettyci, looks cool :+1:

**Comment by staabm** [comment]
pretty ci setup configured via "GitHub App"

will delete php_codesniffer when time allows
