### ISSUE TITLE
Error: Unable to find the socket transport "wss"

### ISSUE THREAD

**Issue by dromansab** [stomp-php/stomp-php#127]
Hello, 

I'm trying to connect to socket that uses the STOMP 1.2 protocol and I'm receiving this message:

"Uncaught Stomp\Exception\ConnectionException: Failed to connect. (1: Unable to find the socket transport "wss" - did you forget to enable it when you configured PHP?"

Is there a way to connect to this socket?

Thanks, 
Dani

**Comment by jmglsn** [comment]
Hey @dromansab,
you need a stream wrapper if you want to connect using a protocol that is not included by default.
Maybe you can provide some more details, right now it's hard to figure out why you would like to use a websocket.

BR
Jens

**Comment by ShawnCorrigan** [comment]
Why not use a websocket? I think this is a valid question. 

> ActiveMQ comes with WebSocket transport which implements Stomp over WebSockets functionality

**Comment by jeeinn** [comment]
I have the same problem.
