### ISSUE TITLE
Compatibility with Artemis broker ?

### ISSUE THREAD

**Issue by gggeek** [stomp-php/stomp-php#134]
From my limited understanding, Apollo has been deprecated by the Apache foundation, and Artemis has picked up the place of next-generation ActiveMQ.
I see that this lib has support and tests to deal with Apollo, but none for Artemis.
q1. will Artemis work out of the box and be identified as an ActiveMQ broker ?
q2. if not, is there any interest in adding support for it ?

**Comment by Norgul** [comment]
+1 Any news about this?

**Comment by jmglsn** [comment]
Sorry, was on parental leave, getting back to business within the next days.

**Comment by jmglsn** [comment]
I started to prepare some of the existing ActiveMQ tests, together with https://hub.docker.com/r/vromero/activemq-artemis and some configuration adaptions like https://activemq.apache.org/components/artemis/documentation/latest/stomp.html#address-settings and it works so far.

**Comment by Norgul** [comment]
Working on my end, thanks
