### ISSUE TITLE
StatefulStomp read function is blocking, any way to make it non-blocking?

### ISSUE THREAD

**Issue by ShawnCorrigan** [stomp-php/stomp-php#136]
I am running this in a loop using Amphp (similar to ReactPHP) and I am running commands based off of the message that comes in. The issue is that using StatefulStomp's read function is blocking, even though it seems that the socket stream itself is set to non-blocking.

Is there any way to make this call non-blocking? I really don't want to block the main thread so I can deal with jobs and their responses without delay.

Thanks in advance.

**Comment by jmglsn** [comment]
Hey @ShawnCorrigan,
not directly, you could try to reduce the read timeout to limit the time that get's lost during an read wait situation.
We planned to provide a version that works with react php but never found the time to start the development on it, sorry.
BR
Jens

**Comment by jmglsn** [comment]
(btw see https://github.com/stomp-php/stomp-php/issues/69)
