### ISSUE TITLE
XML/HTML tags filtered

### ISSUE THREAD

**Issue by NickDaelemans** [stomp-php/stomp-php#138]
Any characters (words) that are starting with '<' are being filtered out using the stomp-php library. When I fetch the messages via the CLI tool or REST API I do get the entire message.

Am I missing something? I expect to receive the entire (non-adapted) XML message.

**Comment by jmglsn** [comment]
Hi @NickDaelemans,
there should be nothing in the library that would do something like this. Can you provide some example code, maybe we can give support than.

**Comment by NickDaelemans** [comment]
I can't really remember what I did to fix it, but it's no longer an issue. So probably it was something on my end.
