### ISSUE TITLE
Getting number of normal and scheduled jobs

### ISSUE THREAD

**Issue by farazpartoei** [stomp-php/stomp-php#140]
Hello,
Is there any API or interface in PHP-STOMP or active-mq itself to fetch number of pending jobs?
I didn't find any in PHP-STOMP docs however fetching 

> http://<ACTIVE-MQ-ADDR>:8161/admin/xml/queues.jsp

gets back with a XML which shows number of jobs plus active broker and consumers.
we could easily call 

> http://<ACTIVE-MQ-ADDR>:8161/admin/scheduled.jsp

to see scheduled tasks. but what if there are thousands of tasks exist there?!! your browser stops quickly

therefore I was looking for a solution for find just NUMBER of pending or scheduled tasks in active-mq scheduler. either through PHP-STOMP or active-mq it self

**Comment by jmglsn** [comment]
Hi @farazpartoei,
stomp itself has nothing that would report the remaining number of messages. So you need to check on active mq side to obtain such number. 
Maybe it's possible to update the broker itself to add the current message amount as a header.
