### ISSUE TITLE
AMQP 1.0

### ISSUE THREAD

**Issue by xiongbenwu** [stomp-php/stomp-php#145]
I want to use AMQP 1.0 ,don't conn

**Comment by staabm** [comment]
Whats the problem? Any errors? How to reproduce?

**Comment by xiongbenwu** [comment]
https://help.aliyun.com/document_detail/142489.html?spm=a2c4g.11186623.6.623.20d03f69DDxtpR

**Comment by staabm** [comment]
Not sure what are you trying to tell us. I will close this issue for now. 

Feel free to provide further information so we have something at hand to help you.
