### ISSUE TITLE
Heartbeat: Heartbeat (server) inactivity not detected

### ISSUE THREAD

**Issue by Nestorfish** [stomp-php/stomp-php#148]
Using ServerAliveObserver alone (no client heartbeat), with no SSL, server network inactivity is not detected.

In this case, I fixed this by changing emptyBuffer() in Observer/AbstractBeats.php to call onPotentialConnectionStateActivity(), instead of onServerActivity() which refreshed lastbeat.

**Comment by marcuswinkler** [comment]
I've just spent some time debugging this issue and I've come to the same conlusion. An `emptyBuffer` should not count as server activity. It is called when the read timeout expires with no data.

Currently, the heatbeat timer is reset on every `emptyBuffer`. This prevents the detection of dead tcp connections. Can easily be confirmed by using firewall rules to drop packets between client and server.

**Comment by c-leroy** [comment]
Thanks!
