### ISSUE TITLE
Add support for durable subscriptions in Artemis

### ISSUE THREAD

**Issue by MPParsley** [stomp-php/stomp-php#154]
Artemis has a slightly different approach to durable subscriptions over ActiveMQ 5.6.

See https://activemq.apache.org/components/artemis/documentation/2.7.0/stomp.html

**Comment by MPParsley** [comment]
Hi @staabm, care to review #151?

**Comment by jmglsn** [comment]
Thank you, I merged the PR and will create a new release soon.
