### ISSUE TITLE
RabbitMQ badConnection Exeption

### ISSUE THREAD

**Issue by vasiliyyudin** [stomp-php/stomp-php#21]
Problem with rabbitMQ connection frame.
https://www.rabbitmq.com/stomp.html
Last string on CONNECTED or RECEIPT has "\n\x00"

Problem on src/Stomp/Connection.php line 317 with "fgets" php function. "fgets" reads the string to the symbol "\n" and never reach "\x00".
Change it to "fread" and problem gone.

You can read details here
http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2008-September/001523.html

**Comment by jmglsn** [comment]
Hi @vasiliyyudin,

can you provide a special situation where this happens? What versions are in use?

I just merged a feature for integration tests on different brokers.
https://github.com/stomp-php/stomp-php/blob/master/tests/Functional/RabbitMq/ClientTest.php 
We need to add your case in this test. There have been some changes at Line 317 in past, that's the reason I want to be sure about it...

**Comment by vasiliyyudin** [comment]
Sure.
I use a vagrant laravel/homestead box.
My RabbitMQ version:
 {rabbitmq_stomp,"Embedded Rabbit Stomp Adapter","3.2.4"},
 {rabbit,"RabbitMQ","3.2.4"},
PHP 5.6.3
stomp-php version 3.0.0

Sitiation:
Install "stomp-php" by composer and run send message part of "binary.php" example. 
Example works, but takes about 120 seconds. 60 seconds for connect and 60 for send message.
How it works:
1) php send connection frame:
CONNECT\n
\n
\x00
2) RabbitMQ returns answer frame:
CONNECTED\n
session:session-byKpRkHZZ3Em9Zu-tyBb_w\n
heart-beat:0,0\n
server:RabbitMQ/3.2.4\n
version:1.0\n
\n
\x00

And we are reading this frame by "fgets" (this function read lines and expect \n or file end) and cant read \x00 byte. Its not a line for fgets.

PS: I changed the version of the program and run RabbitMq/ClientTest.php 
By default - its 14 errors (Failed to connect.) We need to use 61613 port instead of 61030. It is default RabbitMQ STOMP Adapter port. (https://www.rabbitmq.com/stomp.html)

PSS: I changed the port and the tests were run. The first successfully completed, second in progress ( there is a lot of "$y < 100" iterations)
PSSS: I changed function to fread and get this:
..............                                                    14 / 14 (100%)
Time: 10.49 seconds, Memory: 12.25Mb
OK (14 tests, 424 assertions)

**Comment by jmglsn** [comment]
I tried it by myself and had exactly the same problems. 

In an older version we needed `fgets` as the frame parser was not smart enough to handle more than one incoming frame per state. This was changed some time ago. 

This fix will be included in our 3.x  and 4.x releases only. It's included as only change in `3.0.1`.
