### ISSUE TITLE
Stomp-php doesn't support 0-bytes in messages

### ISSUE THREAD

**Issue by arjenm** [stomp-php/stomp-php#23]
When reading messages, the Parser always stops at a 0-byte. It ignores the content-length that was specified in such cases.

I've fixed it using a separate 'getFrameEnd'-method, that supports reading the content-length. See this gist (sorry, no pull request): https://gist.github.com/arjenm/7bab3a10f6d2460c7891

**Comment by jmglsn** [comment]
The current implementation has some lacks regarding Stomp 1.1 / Stomp 1.2 Support. We're currently working on a new version which will bring support for the full Stomp protocol.

I'll check if your fix can be included in version 3 branch too. You can bypass this problem by using a own Connection Class. see https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Stomp.php#L115

**Comment by jmglsn** [comment]
Contained in `3.0.2` 
https://github.com/stomp-php/stomp-php/releases/tag/3.0.2
