### ISSUE TITLE
Stomp-php doesn't handle large messages well

### ISSUE THREAD

**Issue by arjenm** [stomp-php/stomp-php#24]
The current Stomp/Connection-class doesn't handle large messages well. It will read in chunks of 1024 bytes, regardless of whether the messages are exactly that size.

This effectively forces php to timeout on each fread-call, since it will wait until it received 1024 bytes.
That is especially annoying when a server like ActiveMQ sends a message one at a time, rather than streaming them indefinitely.

By using stream_get_line, it can stop at a zero-byte and has thus likely received a full frame (or a part of it, but than it'll read on to the next zero-byte).

See this gist for my implementation: https://gist.github.com/arjenm/4ae508767b1af73c63f5 (sorry, also no pull request)

**Comment by jmglsn** [comment]
I'm almost sure now, that we will use different connection classes for different vendors in future. `stream_get_line seems` to be the best way :+1: for AMQ.

btw. current workspace for Stomp 1.2 support can be found at https://github.com/fin-sn-de/stomp-php/tree/feature/stomp-1.2

**Comment by arjenm** [comment]
Thanks for the reply. I've added another fix to the gist. This fix reads all additional newlines after the end of a frame and ignores them. So it should work for any implementation.

**Comment by jmglsn** [comment]
That's cool, Thank you. It could fail on Stomp 1.2 Clients, they are allowed to send different EOLs. The current parser draft (https://github.com/fin-sn-de/stomp-php/blob/feature/stomp-1.2/src/Stomp/Transport/Parser.php) should support this. But we'll definitely need to improve the Connection class itself.

**Comment by arjenm** [comment]
My fix could fairly easily be adjusted to include both windows and mac line endings; simply als check for \r rather than only \n

I.e. if its \r\n it'll do two reads.
It is unfortunate that the knowledge of how a Frame ends is spread amongst the Connection and Parser.

The main issue we encountered was that the client and ActiveMQ would turn out to be waiting on each other. ActiveMQ was waiting for an ack (due to prefetch size of 1), while the client was waiting for more data to read (that last part was actually partially an artifact of some other part of our consumption-code).

Stopping exactly at the end of a Frame seems to be the best solution, but it is unfortunate a Frame has no clearly determined end.

**Comment by jmglsn** [comment]
That's true.
I don't like that shared knowledge too. 
That "waiting problem" is something I had to deal with recently. I'm not sure if it's something that's affecting the real life. Might depend on usage, but in my last projects most clients had to deal with mass data, so there was always new data to consume. Well, at the point no new data arrives it takes some time until the client acts as expected.
I'm sorry that I can't include your improvements right now. I'll back at this project in about 5 days..

**Comment by jmglsn** [comment]
Mixed this up with the other issue, has been a long day ;)
(see https://github.com/stomp-php/stomp-php/pull/25)
