### ISSUE TITLE
Stomp doesn't disconnect when host fails

### ISSUE THREAD

**Issue by arjenm** [stomp-php/stomp-php#28]
When a host fails, the Stomp::disconnect-method doesn't work.

This is caused by the fact that the writeFrame-method will throw an exception, and thus the $this->connection->disconnect() method is never called.

This gist should fix that: https://gist.github.com/arjenm/f603b982f3ff701f3462

It simply moves the disconnect outside of the try/catch.

A larger issue is that the whole failover-functionality actually doesn't really do much; it only operates at connection-time: try each host and if none works it throws an exception.
But failover suggests it'll try another host as soon as the currently connected one doesn't work anymore. Similar to what the java-version of the activemq-client does. That is a rather more complicated scenario (it would probably be a good idea to subclass or wrap Connection)

Anyway, the above issue also prevents 'manual' failover (i.e. disconnect + reconnect) since the connection will never actually disconnect and thus isConnected will not return false so a new connection is never attempted.
One could just delete the Stomp-instance, but that will lead to a bit of resource-leakage (the socket is not closed on the php-side untill the program stops).

**Comment by jmglsn** [comment]
I'll check if there is a good way to handle transparent reconnect on failing hosts in version 4. Might be simple to handle within the different states. For our current version it's almost impossible...
