### ISSUE TITLE
Async usage does not always complete to write the data

### ISSUE THREAD

**Issue by staabm** [stomp-php/stomp-php#33]
Using the client in async mode sometimes produces inconsistent results, because `fwrite` had no time to write all the data to the stream[1] when `exit()` is called.

`fwrite` does not always write all the bytes you pass to it. It returns the number of bytes actually written.
As the client does not support some kind of shutdown handling its not possible to gracefully stop a script which uses the this stomp client in async mode. 

I am not yet sure how this can be fixed without major refactoring of the underlying classes.

[1] https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Network/Connection.php#L304

**Comment by jmglsn** [comment]
We'll need to ensure that the result of `writeFrame` is reliable. From my point of view this applies to sync mode as well. At least the doc examples implies that. http://php.net/fwrite.

This must be fixed in all versions...

**Comment by staabm** [comment]
You might be right. Havent used the client with sync writes yet.

**Comment by jmglsn** [comment]
We could provide a own Connection class for Async mode. I didn't use the client in async mode yet, is your use case a producer?

**Comment by staabm** [comment]
In my use case I am building a deamon doing reads and wirtes at te same time. I experienced the error while producing and pushing results though.

**Comment by staabm** [comment]
At best we could check writeability with stream_select and make sure that all data is written properly in e.g. A shutdown_function (or some other api method which can be used before a `exit` call)

**Comment by jmglsn** [comment]
But we'll need to keep the data which has to be written to the stream until the destructor / shutdown is called. If I got the example right fwrite not only returns the amount of written bytes, it also wont remember any not written byte. So it needs another call with the not yet written data. This would lead to an mixup if writeFrame would not track this data. First approach is to fix it within that function, next would be an connection class which could provide an "unsafe" writeFrame but this would need keep track of all unwritten data. Those class must provide methods for a safe shutdown.
I'll provide a patch for the safe writeFrame today, but I'm not sure if a "AsyncConnection" class is safe, from my point of view this would only be ok for a producer. Or it needs a much deeper coupling - since any operation expecting a receipt would require that the connection has send all data.

**Comment by staabm** [comment]
A ugly fix could invoke `fwrite` in a loop until everything was written. 

Having the remaining bytes remembered somewhere and written later on when stream gets ready/writable would be a more performant and better solution which can be targetted later on IMO

**Comment by staabm** [comment]
Just ckecked some amp libs, which also solve the problem we have here.

We need to check writability with stream_select and a write-buffer, something along the lines of https://github.com/amphp/mysql/blob/master/lib/Connection.php#L1161

**Comment by jmglsn** [comment]
I got lost somehow - maybe we don't name the same. Sync in my option is just the receipt handling of this lib right now, which won't change the connection behavior at this moment. The fwrite problem seems to be present regardless if we expect receipts or not.
You're pointing to event driven php or?

**Comment by staabm** [comment]
My point is about non-blocking io, which is activaed in the connection using `->sync` flag

**Comment by staabm** [comment]
I just realized that the `sync` flag does not what I expected it todo.
the client defines `sync` as 

```php
    /**
     * Perform request synchronously
     *
     * @var boolean
     */
    private $sync = true;
```

which brought me to the conclusion that the client is doing non-blocking reads/writes, but actually the client always does blocking io (it never invokes `stream_set_blocking`). `stream_select` is used as a means to prevent doing blocking `fwrite/fread`, so it just feels like non-blocking io in some situations.

**Comment by jmglsn** [comment]
I was confused too, you never now if there is a hidden feature ;)
But we can introduce a connection that actually works with `stream_set_blocking` - next year :)

**Comment by staabm** [comment]
Atm I can work with the version we have right now. 

Adding async capabilities also will require the concept of promises...

**Comment by jmglsn** [comment]
Might be a task or something to keep in mind during #34.
