### ISSUE TITLE
Use external event reactor instead of implementing one in this lib

### ISSUE THREAD

**Issue by staabm** [stomp-php/stomp-php#34]
Using a event reactor like https://github.com/amphp/amp or https://github.com/reactphp/event-loop would reduce complexitiy of this lib, as you could borrow e.g. loop/socket/connection logic from one of the mentioned frameworks. 

The lib would also benefit from the async capabilities of such a framework, meaning one could use the reactor to also do other async things while writing/reading to the queue, like async db queries, async filesystem operations etc.

It would also mean that his lib could concentrate on the main task - stomp itself and interopability between different queue types etc. 

There are a lot of possibilities see e.g. https://github.com/amphp

**Comment by jmglsn** [comment]
I like that idea, it would be something like https://github.com/reactphp/stomp. Maybe we can start a new repository for that? But at this time we would need some help for that, are you interested?

**Comment by staabm** [comment]
I would be willing to help in case we based it on amphp/amp

**Comment by jmglsn** [comment]
That's great! Actually currently I don't have that much time to work here, but I'll try to take time for this. Btw you got invited. I think my free time amount will increase at 02/16 that will be the time I can bring in some more input.

**Comment by staabm** [comment]
Ok, I can start initial work in a repos under my name, we can transfer the repos to whatever gh-org we feel it should belong to.

**Comment by staabm** [comment]
After exploring the lib in more detail I realized that this lib doesnt really use a event reactor and non-blocking streams but ises stream_select() to prevent running into blocking IO.

For the time beeing this is good enough for my use-cases therefore I will close this süissue for now.

**Comment by staabm** [comment]
But to be hones, I am not sure whether we need a loop arreound the `fwrite`s to make sure all the bytes are written in https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Network/Connection.php#L304

**Comment by jmglsn** [comment]
I'm not sure if the documentation note is new, but it says that it could end before the complete data is written, so we should wrap it inside a loop. (To be honest, I never used a loop around fwrite.)

**Comment by staabm** [comment]
@bwoebi will `fwrite` when used on a blocking stream always write all the data?

**Comment by bwoebi** [comment]
@staabm Yes, unless the connection is aborted (and eventually intervening signals if configured so via pcntl). … That's quite the point of blocking to write all data.

**Comment by bwoebi** [comment]
Ad. the problem with libs using stream_select() is that one is unable to use them inside non-blocking applications as stream_select() itself blocks.

It's typically more useful to have an underlying async layer (using https://github.com/async-interop/awaitable and https://github.com/async-interop/event-loop) and a thin separate decorating wrapper translating these into directly usable functions for sync environments.
This way everyone, sync as well as async app can use it easily.
