### ISSUE TITLE
Messages with 0-bytes can cause a read-exception

### ISSUE THREAD

**Issue by arjenm** [stomp-php/stomp-php#39]
After this patch, the handling of 0-bytes was improved: 
https://github.com/stomp-php/stomp-php/issues/24

But I failed to notice one particular issue when reporting it. Whenever there is a 0-byte right _after_ the current position of the socket, the (next) result from stream_get_line() will be an empty string.

I encountered it with a message that had such a 0-byte after 8192 bytes, but its probably easier to trigger with a message that contains a few 0-bytes in a row.

The fix is very easy, just remove this check in the Connection::readFrame-method:
`$read === ''` 

With fread that empty-scenario should never happen but was possibly an indication of an error. With stream_get_line its a valid scenario for whenever there is a 0-byte as the first byte in the upcoming data.

This issue exist in both the 3.x-branch (which I'm using) and (from looking at the code) the master-branch.

**Comment by staabm** [comment]
I guess this line[1] should read

```
if ($read === false) {
  throw new ConnectionException('Was not possible to read data from stream.', $this->activeHost);
}

if ($read === '') {
  return false;
}
```


[1] https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Network/Connection.php#L328

**Comment by arjenm** [comment]
Afaik it should just treat that empty string as valid data. I.e. continue the while-loop and add a 0-byte to the buffer, before doing another read.

Say the message contains this data: theHeaders\n\ndataPart1\00\00dataPart2\00
In the current scenario, this would be roughly the method trace:

1. stream_get_line() 
2. add "theHeaders\n\ndataPart1" to the buffer of the Parser
3. add "\00" to the buffer, since that previous string was not 8192 bytes long
4. stream_get_line()
5. receive an empty-string -> throw exception

In your variant it would become:

1. stream_get_line() 
2. add "theHeaders\n\ndataPart1" to the buffer of the Parser
3. add "\00" to the buffer, since that previous string was not 8192 bytes long
4. stream_get_line()
5. receive an empty-string -> return false and leave a partially parsed frame in the Parser's buffer and on the socket

Even though that would probably continue the read in the next readFrame, its still kinda dangerous and also would not add the 0-byte in the buffer. Thus changing the message's content (and cause a mismatch with the Content-Length header).

In my variant it would be:

1. stream_get_line() 
2. add "theHeaders\n\ndataPart1" to the buffer of the Parser
3. add "\00" to the buffer, since that previous string was not 8192 bytes long
4. stream_get_line()
5. receive an empty-string and do nothing (well addData, but that could be skipped if necessary)
6. add "\00" to the buffer, since that previous string was not 8192 bytes long
7. stream_get_line()
8. receive an empty-string and do nothing (well addData, but that could be skipped if necessary)
9. add "\00" to the buffer, since that previous string was not 8192 bytes long
10. and then the same for "dataPart2"

So just to be sure, I'd expect this would be correct:
```
do {
            $read = @stream_get_line($this->connection, 8192, Parser::FRAME_END);
            if ($read === false /* remove this: || $read === ''*/) {
                throw new ConnectionException('Was not possible to read data from stream.', $this->activeHost);
            }
            $this->parser->addData($read);
            // Include zero-byte back at the end
            if (strlen($read) != 8192) {
                $this->parser->addData(Parser::FRAME_END);
            }
        } while (!$this->parser->parse());
```
And if you really don't want to append a empty string, the addData-call can be made optional whenever $read === ''

**Comment by jmglsn** [comment]
Fix will be included in next release, just waiting for #40.

**Comment by ganeko** [comment]
@jmglsn my PR #111 will fix this problem, yes.

**Comment by gabrielspiteri-highlight** [comment]
@arjenm how come the check for $read = '' is still there?

**Comment by arjenm** [comment]
@gabrielspiteri-highlight I don't know, I don't maintain this library. I just reported the bug initially and it now reappeared.
