### ISSUE TITLE
Exists a way to set the read timeout in a StatefulConnection?

### ISSUE THREAD

**Issue by surrealcristian** [stomp-php/stomp-php#41]
Hello everyone:

I'm extracting elements from a queue, calling the method `read` from a `StatefulConnection` instance.

When the queue becomes empty, my script keeps waiting 60 seconds, until the `read` method returns false.

In https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Network/Connection.php#L55, i see a read timeout of 60 seconds, hardcoded.

Exists a way to set or configure the read timeout in a StatefulConnection?
If not, is possible implement it?

Thanks!

**Comment by staabm** [comment]
Doesnt `setReadTimeout`[1] work for you?

[1] https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Network/Connection.php#L167

**Comment by surrealcristian** [comment]
Yes, the next code works for me:

```
$client = new Client("tcp://$host:$port");

$conn = $client->getConnection();
$conn->setReadTimeout(5);

$stomp = new StatefulStomp($client);
```

Thanks.
