### ISSUE TITLE
Subscription Id on ackownledgement.

### ISSUE THREAD

**Issue by thoroc** [stomp-php/stomp-php#46]
Hi,

I am working with an ActiveMQ and using stomp-php, I am getting the following error:
```
    [Stomp\Exception\ErrorFrameException]                            
    Error "ACK received without a subscription id for acknowledge!" 
```
But for the life of me, I cannot seems to find a method to acknowledge that would require a subscription ID. 

The code is as follow:

```php
class StompClient
{
    private $stomp;

    public function __construct($endpoint, $timeout = 10)
    {
        $connection = new Connection($endpoint);
        $connection->setReadTimeout($timeout);

        $client = new Client($connection);
        $client->setLogin(self::TEST_USER, self::TEST_PASSWORD);

        $this->stomp = new StatefulStomp($client);
    }

    public function receive($queue)
    {
        $subId = $this->stomp->subscribe($queue, null, 'client');
        echo "> Subscription ID:'".$subId."'\n";

        $frame = $this->stomp->read();
        if (false !== $frame) {
            echo "> Received message with body '$frame->body'\n";
            $this->stomp->ack($frame);
        } else {
            echo "> Failed to receive a message\n";
        }

        $this->stomp->unsubscribe($subId);

        $body = json_decode($frame->body, true);
        $msgId = $frame->getMessageId();

        return json_encode([
            'message' => $body,
            'id' => $msgId,
        ]);
    }
}
```
Where am I doing something wrong?

~thoroc

**Comment by jmglsn** [comment]
Hey thoroc,

what AMQ version you're using?

jens

**Comment by thoroc** [comment]
I think it is either 5.7 or 5.9. It's hidden behind a fuse server, for which I have no direct access apart from a hawtio web interface. :/

**Comment by jmglsn** [comment]
I tried your code with 5.9.1 and it worked as expected.

You get more details about the server by adding

```php

       $client = new Client($connection);
       $client->setLogin(self::TEST_USER, self::TEST_PASSWORD);
       var_dump($client->getProtocol()->getVersion());
       var_dump($client->getProtocol()->getServer());
```

I remember that we had some trouble with older AMQ versions and differnt ACK modes. 
You can also try to use a specific version, just add something like after `new Client...`
```php
      $client->setVersions([Stomp\Protocol\Version::VERSION_1_0]);
```

If you provide the used version I'll try to reproduce the failure. Another interesting resource is http://activemq.apache.org/maven/apidocs/src-html/org/apache/activemq/transport/stomp/ProtocolConverter.html just search for the error message.

**Comment by staabm** [comment]
I am successfully using activemq with stomp1.0

**Comment by jmglsn** [comment]
@thoroc is the problem solved?

**Comment by thoroc** [comment]
Sorry, let me check.

**Comment by thoroc** [comment]
Ok, I have tried version 1.0 as suggested. and the error message just vanished. 

for ref, the code giving the error is the following (line 409-412):
``` java
        String subscriptionId = headers.get(Stomp.Headers.Ack.SUBSCRIPTION);
        if (subscriptionId == null && this.version.equals(Stomp.V1_1)) {
            throw new ProtocolException("ACK received without a subscription id for acknowledge!");
        }
```

**Comment by staabm** [comment]
we initially also had problems with stomp 1.1 and therefore use stomp1.0 (by using a different api endpoint). I didnt check what the origin of the problems with stomp 1.1 were with AMQ.
