### ISSUE TITLE
Choose coding style standard and fix codebase

### ISSUE THREAD

**Issue by chuhlomin** [stomp-php/stomp-php#5]
There are not many options here:
* PSR1/2
* Symfony2
* Zend
* PEAR
* *Anything else*?

As for me, PSR if preferable, but I'm ok with any of them. We just should choose one.

**Comment by jmglsn** [comment]
PSR 2 is fine :)

**Comment by chuhlomin** [comment]
Nice, then, PSR1/2, decided.
I would like to add phpcs checker and fix code-style after merge #4.

**Comment by jmglsn** [comment]
That's cool. Just merged #4, so you're ready to go :)
