### ISSUE TITLE
NULL octets in body aren't handled properly

### ISSUE THREAD

**Issue by andrewbelcher** [stomp-php/stomp-php#53]
STOMP specification states:

> The SEND, MESSAGE and ERROR frames SHOULD include a content-length header if a frame body is present. If a frame's body contains NULL octets, the frame MUST include a content-length header. The header is a byte count for the length of the message body. If a content-length header is included, this number of bytes MUST be read, regardless of whether or not there are null characters in the body. The frame still needs to be terminated with a null byte.
> - https://stomp.github.io/stomp-specification-1.1.html#Header_content-length

So it is valid for body to contain NULL octets and the `content-length` header should be respected _over_ NULL octets as an end character.

However, `\Stomp\Network\Connection::readFrame` and `\Stomp\Transport\Parser::detectFrameEnd` both simply look for a NULL octet (or the end of the stream). This results in messages where the body contains a NULL octet getting truncated (in my case the body is gzip compressed).

**Comment by staabm** [comment]
thx for catching this. could you provide a failing unit test? maybe even a patch?

**Comment by andrewbelcher** [comment]
There is a PR that I think fixes it. I think contrary to my initial thinking, `\Stomp\Network\Connection::readFrame` is actually fine as it is.

**Comment by andrewbelcher** [comment]
Sorry @staabm, just seen your comment. I will see if I can get a test written when I get a gap, but the PR above fixes the problem for mw.

**Comment by andrewbelcher** [comment]
I have just pushed an update to #54 which includes test coverage. Locally it fails without the fix and passes with it.

**Comment by jmglsn** [comment]
@andrewbelcher Please have a look at https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Transport/Parser.php#L219.

**Comment by jmglsn** [comment]
My fault, sorry... to long day...

**Comment by andrewbelcher** [comment]
@jmglsn wasn't sure whether you still had a question, but in case you did - the problem was that because both `$this->expectedBodyLength` and `($this->bufferSize - $this->offset) >= $this->expectedBodyLength` were in the same `if (...)`, a failure of the 2nd caused it to continue to the `elseif` which would look for the NULL octets and therefore mark it as complete.

**Comment by jmglsn** [comment]
Yesterday I just thought "hey I did something against the null-byte stuff" had a quick look at my code and: yes it's there.
A few moments later I reviewed the PR and yep, it's there and it will not work proper.

So your PR and the reported Issue is perfect. Thank you for your input :)
