### ISSUE TITLE
How to send persistent messages?

### ISSUE THREAD

**Issue by xiaoxing598** [stomp-php/stomp-php#58]
I can't find the function to send persistent messages.

**Comment by xiaoxing598** [comment]
Persistent messages look like the following:
```
Message ID  	Correlation ID  	Persistence ↓	Priority  	Redelivered  	Reply To  	Timestamp  	Type  	Operations  
ID:host104-49083-1471844149725-4:1:1:1:2		Persistent	0	false		2016-08-22 13:38:26:153 CST		Delete
```

Non persistent messages are like this:
```
Message ID  	Correlation ID  	Persistence ↑	Priority  	Redelivered  	Reply To  	Timestamp  	Type  	Operations  
ID:host104-44175-1471850521652-5:1:-1:1:1		Non Persistent	4	false		2016-08-22 15:23:26:743 CST		Delete
```

**Comment by jmglsn** [comment]
Persistent Messages are a broker specific feature, that's the reason there is no default function for that. But we provide a set of util classes with special helper sets. I'm not sure if you're using ApolloMQ or ActiveMQ but you might find some tests for persistent messages within our tests. Please have a look https://github.com/stomp-php/stomp-php/blob/master/tests/Functional/ActiveMq/ClientTest.php#L340 and https://github.com/stomp-php/stomp-php/tree/master/src/Stomp/Broker/ActiveMq/Mode.
Please provide your broker version for more help.

**Comment by xiaoxing598** [comment]
I need to send persistent queue messages in ActiveMQ, but not in the framework, because I only see the framework in which to send persistent subscriptions. In order to achieve my goal, I will some destructive framework source code have been modified, so you can now to send the ActiveMQ persistent queue news, but my changes may undermining stability in the framework, especially when using other MQ service. This defect may occur, which is why I didn't contribute code.

As I would like to use the fault transfer function, write the following in my code:
```
$this->producer = new StatefulStomp(
    new Client('failover://(' . $address . ')?randomize=false')
);
$this->producer->send('/queue/' . $destination, new Message($msg), ['persistent' => 'true']);
```

Here are some of my modifications to the framework:
```
IStateful.php
public function send($destination, Message $message, array $header = []);

StatefulStomp.php StateTemplate.php ConsumerState.php
public function send($destination, Message $message, array $header = [])
    {
        return $this->state->send($destination, $message, $header);
    }

```

**Comment by jmglsn** [comment]
You can just add the required header to your message. 
I already forgot that we included this simple hack ;)

This would look like this:
```php
$message = new Message('body', ['persistent' => 'true']);
```
or even
```php
$message = new Message('body');
$message['persistent'] = 'true'
```
That should work together with `send` from `StatefulStomp`.

**Comment by xiaoxing598** [comment]
Look, I've got the problem complicated. You're supposed to be the best solution.
