### ISSUE TITLE
Support: Reporting when there is no data to receive

### ISSUE THREAD

**Issue by andrewbelcher** [stomp-php/stomp-php#59]
Wondering if you can give me any pointers. Summarised, my code is:

```
$stop = time() + 60;
$client = new \Stomp\Client('uri');
$client ->connect();
$stomp = new \Stomp\SimpleStomp($client);
$stomp->subscribe('queue');

while ($stomp && time() < $stop) {
  if ($frame = $stomp->read()) {
    // Process our frame.
    // Update our 'last processed' time.
  }
  else {
    // Update our 'last processed' time.
    sleep(1);
  }
}
```

However, I am getting periods where my 'last processed' time is not getting updated. This is happening in the middle of the night, so my assumption is that there is just no data being sent, however, I would expect the `else` to still run. It looks like `$stomp->read()` is waiting until there is data, but I would have expected it to return after 60 seconds (the default for `\Stomp\Network\Connection::$readTimeout`).

**Comment by jmglsn** [comment]
Maybe the broker is sending `NULL Bytes` to keep the connection alive, this combined with our 8K buffer size could lead to this situation, but I'm not sure.
Which broker / version is being used?

**Comment by andrewbelcher** [comment]
According to the `CONNECTED` frame, it is ActiveMQ version 1.2. The heartbeat is set to `0,0`, so I would not be expecting it to send any data.

Would enabling a heartbeat resolve the issue, or would that have the same issue as an `EOL` would result in it thinking there is data to read and getting stuck gobbling new lines?

**Comment by staabm** [comment]
could you debug what https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Network/Connection.php#L397-L404 will do when this situation occurs?

**Comment by staabm** [comment]
it sounds like we either run into a blocking fread()[1] or in a blocking stream_get_line()[2]

[1] https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Network/Connection.php#L397
[2] https://github.com/stomp-php/stomp-php/blob/master/src/Stomp/Network/Connection.php#L346

**Comment by andrewbelcher** [comment]
Would using `stream_set_timeout($this->readTimeout[0], $this->readTimeout[1])` in `connect()` resolve this? Looking at `fread()`, if there is no timeout, it will continue until it reads the requested amount of data or gets an EOF.

**Comment by andrewbelcher** [comment]
I've created #60 which demonstrates that this does fail with a heartbeat.

The spec is that if the heartbeat header isn't provided, it's treated as `0,0`, so it shouldn't be sending a heartbeat... Which means my issue may be an upstream one rather than here...

**Comment by andrewbelcher** [comment]
To be honest, I don't really know exactly what is going on overnight - not sure how to watch the stream to see if it is sending NULL bytes. From my understanding of the code, we should only get into this scenario if we are being sent something, but I don't think ActiveMQ should be sending anything unless we've said we will receive heartbeats, so I'm a little at a loss...

**Comment by jmglsn** [comment]
@andrewbelcher This should be solved with the latest versions, for sure with https://github.com/stomp-php/stomp-php/releases/tag/4.4.0 as we now changed to non-blocking IO.
