### ISSUE TITLE
fwrite in Connection.php not working for UTF-8

### ISSUE THREAD

**Issue by patStar** [stomp-php/stomp-php#63]
Today I tried to send a String containing the name "Krüger" via Stomp. The strlen method in combination with fwrite in Connection.php Line 323 is not working for me since the string "Krüger" has an UTF-8 strlen of 6 but is interpreted as ISO within the fwrite method. So on the other side I get the string "Krüge" without the r. Sending "Krüüger" results in "Krüüg". This may be due to the fact that fwrite is not binary safe (see: http://stackoverflow.com/questions/6336586/fwrite-and-utf8). I fixed the issue by overwriting the Connection class and using mb_strlen ( $string, 'ISO-8859-1') instead of strlen.

Perhaps I have overlooked something. 

Greetings!

P4T

-- edit: The first missing character at the end of the Message "Krüger" is not the "r" its the END_FRAME char. That's the main problem since the message frame is intepreted as not closed!

**Comment by jmglsn** [comment]
What broker / versions are you using?
I just updated the test suite to send some utf-8 messages and it worked as expected.

**Comment by staabm** [comment]
I guess the behavior depends on mb func overloading?

**Comment by staabm** [comment]
Or php-version.. maybe even php internal encoding (php.ini)

**Comment by jmglsn** [comment]
How do you get the content you're sending? Can you give us a code example and some details about php and stomp broker version.

**Comment by patStar** [comment]
I'll give you a more detailed example but to start:

> $name = 'Krüger';
fwrite(fopen('someStream','w'),$name,strlen($name));
static::assertEquals($name,file_get_contents('someStream'));

returns

> Failed that two strings are equal.
Expected :'Krüger'
Actual   :'Krüge'

on my system.

Can you reproduce this behavior?

**Comment by staabm** [comment]
cannot repro: https://3v4l.org/vAjRH

**Comment by patStar** [comment]
Thx! So it's hidden somewhere in our php.ini I guess.

**Comment by jmglsn** [comment]
Is the source code file encoding correct?
Check if `default_charset = "utf-8"` is enabled in your php.ini.
