### ISSUE TITLE
Empty host when failover url contains underscore

### ISSUE THREAD

**Issue by campru** [stomp-php/stomp-php#67]
I have started using this library and I found an issue when I am running my continuous integration with this library (based on docker multi instance. Docker when you use images, they resolve the // to __). The error is the following:
```
Bad Broker URL failover://(tcp://campru__activemq:61613)?randomize=false. Check used scheme! (Host: )
```
The problem is that underscore is not added in the regular expression in the class
```
Stomp\Network\Connection.php
```
to get the scheme, host and options but this is a character allowed in the domain. For this reason my suggestion is modify the regex to something like this
```
|^(([a-zA-Z0-9]+)://)+\(*([a-zA-Z0-9\.:/i,-_]+)\)*\??([a-zA-Z0-9=&]*)$|i
```
I have already created a pull request with the changes that I would do to fix that: https://github.com/stomp-php/stomp-php/pull/66. Let me know if there is something wrong

**Comment by jmglsn** [comment]
Thanks for your pull request https://github.com/stomp-php/stomp-php/pull/66 👍
