### ISSUE TITLE
Documentation seems to be outdated and does not reflect latest branch

### ISSUE THREAD

**Issue by azngeek** [stomp-php/stomp-php#71]
When trying to follow the documentation i saw that it does not match with the code from the latest master branch.

For Example: https://github.com/stomp-php/stomp-php/wiki/First-example

**Comment by staabm** [comment]
any change you would suggest?

**Comment by jmglsn** [comment]
Have you seen our examples repository? https://github.com/stomp-php/stomp-php-examples
