### ISSUE TITLE
drop php 5.5/5.6 compat

### ISSUE THREAD

**Issue by staabm** [stomp-php/stomp-php#78]

**Comment by jmglsn** [comment]
+1

**Comment by MPParsley** [comment]
We should probably drop support for all versions of php below 7.3.

See https://www.php.net/supported-versions.php

**Comment by whikloj** [comment]
I agree with @MPParsley, but as 5.0.0 has been out for years. I'm closing this as completed with https://github.com/stomp-php/stomp-php/releases/tag/5.0.0 and will move the 7.3 discussion to #176
