### ISSUE TITLE
Travis build hangs for 10min -> build aborted

### ISSUE THREAD

**Issue by staabm** [stomp-php/stomp-php#79]
I can see several builds halting at the very same unit test, across different php versions. feels like a race condition somewhere..

I guess its the same unit test, because of "same number of dots" in the phpunit progress bar

```
$TRAVIS_BUILD_DIR/vendor/bin/phpunit

PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Warning:	The Xdebug extension is not loaded

		No code coverage will be generated.

................
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

occurred on e.g. https://github.com/stomp-php/stomp-php/pull/77/commits/24ececda31f5255fcaac02bcf5e8a928693bfd0b

https://travis-ci.org/stomp-php/stomp-php/jobs/265151314
https://travis-ci.org/stomp-php/stomp-php/jobs/265151316

**Comment by staabm** [comment]
sometimes re-starting the build fixes the error.. but sometimes it appears again

**Comment by jmglsn** [comment]
We could add the verbose flag. This should display the current test.

**Comment by staabm** [comment]
Could you set the flag, not sure where it needs to be...

**Comment by jmglsn** [comment]
Ok, once I'm back on keyboard.

**Comment by jmglsn** [comment]
I see a chance that this is caused by `dist: trusty`, so I'll add `dist: precise` here.

**Comment by jmglsn** [comment]
Looks like this fixed it for the moment, but we need to track this. From my point of view it's more reliable to change back to the docker infrastructure. But this will require some additional steps.

**Comment by jmglsn** [comment]
We also need to check that the services are started as required. see https://gist.github.com/jmglsn/d3f0dd15ad7b00b689ca689d74e51a90#file-travis-log-service-missing-log

**Comment by staabm** [comment]
:+1:

**Comment by jmglsn** [comment]
We should enable `--enforce-time-limit` to do so we also need to add the invoker package during build time. see comments in #87

**Comment by jmglsn** [comment]
Finally? :)

**Comment by staabm** [comment]
Lets see how it goes for the next PRs
