### ISSUE TITLE
Register Project at Packagist

### ISSUE THREAD

**Issue by jmglsn** [stomp-php/stomp-php#8]
This project is meant to be the follow up of dejanb/stomp-php, so we need to register it at php package repository.
Package meta from dejanb/stomp-php should be updated to declare this project as replacement.
This step should be performed right after release 3.0.0.

**Comment by riskawarrior** [comment]
Hi,

What is required for the 3.0.0 release? Will be some kind of documentation (as the original FuseStomp documentation is own for weeks now).

**Comment by jmglsn** [comment]
Hi @riskawarrior,

we could update all existing examples. Right now I don't plan a new documentation for 3.0.
In meantime https://stomp.github.io/ should be enough to start.

**Comment by jmglsn** [comment]
Docs at https://github.com/stomp-php/stomp-php/wiki.
Package is now out at https://packagist.org/packages/stomp-php/.
Version 3.0.0 finished!
