### ISSUE TITLE
disconnect this repos from dejanb/stomp-php

### ISSUE THREAD

**Issue by staabm** [stomp-php/stomp-php#98]
github code-search only works for the upstream/origin repos and doesnt work for forks. it would be great we could separate this project from the initial codebase.

keeping authorship is of course very important, so we should give credit in the README etc.

**Comment by jmglsn** [comment]
+1 I'm on vacation right now, but if you have a plan - go for it.
Greetings from Italy ;)

**Comment by jmglsn** [comment]
I asked the github support to "unfork" us let's see what happens.

**Comment by jmglsn** [comment]
That worked :)

I’ll update the readme later, in order to update the credits.

**Comment by staabm** [comment]
thank you!
